# Generated by Django 2.2.12 on 2022-04-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_wages'),
    ]

    operations = [
        migrations.AddField(
            model_name='wages',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
