# Generated by Django 2.2.12 on 2022-04-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_wages_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wages',
        ),
    ]
