# Generated by Django 2.2.12 on 2022-04-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_wages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wages',
            new_name='Wage',
        ),
    ]
