# Generated by Django 2.2.12 on 2022-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20220414_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('PL', 'English Premier League'), ('CL', 'Champions League'), ('FAC', 'Football Association Cup'), ('EFL', 'English Football League Cup'), ('CWC', 'FIFA Club World Cup'), ('USC', 'UEFA Super Cup'), ('FACS', 'FA Community Shield')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='titles',
            field=models.ManyToManyField(to='main_app.Trophy'),
        ),
    ]
