# Generated by Django 2.2.12 on 2022-04-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20220418_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
